name: saytask
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1
  intl: ^0.19.0
  toggle_switch: ^2.3.0
  simple_circular_progress_bar: ^1.0.2
  lucide_icons: ^0.257.0
  flutter_toggle_tab: ^1.5.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^9.0.0
  another_flushbar: ^1.12.32
  image_picker: ^1.2.0
  haptic_feedback: ^0.5.1+1
  speech_to_text: ^7.0.0
  uuid: ^4.5.1
  flutter_advanced_switch: ^3.1.0
  flutter_tabler_icons: ^1.43.0
  file_picker: ^10.3.3
  timelines_plus: ^1.0.8
  record: ^6.1.2
  path_provider: ^2.1.1
  http: ^1.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  webview_flutter: ^4.7.0

#  firebase_core: 2.17.0
#  firebase_auth: 4.10.1
#  sign_in_button: 3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

